version: "3.8"

services:
  agent:
    build:
      context: .
    image: ghcr.io/h0n9/msg-lake
    command: ["agent", "--mdns"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: "1.0"
          memory: 256M
        reservations:
          cpus: "1.0"
          memory: 256M
  nginx:
    depends_on:
      - agent
    image: nginx:1.23.4-alpine3.17
    restart: always
    volumes:
      - ./misc/nginx.conf:/etc/nginx/conf.d/msg-lake.conf:ro
    ports:
      - 8080-8082:8080
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
    deploy:
      replicas: 3
  client:
    depends_on:
      - nginx
    image: ghcr.io/h0n9/msg-lake
    command: ["client", "--host", "nginx:8080"]
    deploy:
      replicas: 0
