// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the gRPC Swift generator plugin for the protocol buffer compiler.
// Source: proto/msg-lake.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/grpc/grpc-swift

import GRPCCore
import GRPCProtobuf

// MARK: - MsgLake

/// Namespace containing generated types for the "MsgLake" service.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
internal enum MsgLake {
    /// Service descriptor for the "MsgLake" service.
    internal static let descriptor = GRPCCore.ServiceDescriptor(fullyQualifiedService: "MsgLake")
    /// Namespace for method metadata.
    internal enum Method {
        /// Namespace for "Publish" metadata.
        internal enum Publish {
            /// Request type for "Publish".
            internal typealias Input = PublishReq
            /// Response type for "Publish".
            internal typealias Output = PublishRes
            /// Descriptor for "Publish".
            internal static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "MsgLake"),
                method: "Publish"
            )
        }
        /// Namespace for "Subscribe" metadata.
        internal enum Subscribe {
            /// Request type for "Subscribe".
            internal typealias Input = SubscribeReq
            /// Response type for "Subscribe".
            internal typealias Output = SubscribeRes
            /// Descriptor for "Subscribe".
            internal static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "MsgLake"),
                method: "Subscribe"
            )
        }
        /// Descriptors for all methods in the "MsgLake" service.
        internal static let descriptors: [GRPCCore.MethodDescriptor] = [
            Publish.descriptor,
            Subscribe.descriptor
        ]
    }
}

@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension GRPCCore.ServiceDescriptor {
    /// Service descriptor for the "MsgLake" service.
    internal static let MsgLake = GRPCCore.ServiceDescriptor(fullyQualifiedService: "MsgLake")
}

// MARK: MsgLake (server)

@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension MsgLake {
    /// Streaming variant of the service protocol for the "MsgLake" service.
    ///
    /// This protocol is the lowest-level of the service protocols generated for this service
    /// giving you the most flexibility over the implementation of your service. This comes at
    /// the cost of more verbose and less strict APIs. Each RPC requires you to implement it in
    /// terms of a request stream and response stream. Where only a single request or response
    /// message is expected, you are responsible for enforcing this invariant is maintained.
    ///
    /// Where possible, prefer using the stricter, less-verbose ``ServiceProtocol``
    /// or ``SimpleServiceProtocol`` instead.
    internal protocol StreamingServiceProtocol: GRPCCore.RegistrableRPCService {
        /// Handle the "Publish" method.
        ///
        /// - Parameters:
        ///   - request: A streaming request of `PublishReq` messages.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A streaming response of `PublishRes` messages.
        func publish(
            request: GRPCCore.StreamingServerRequest<PublishReq>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.StreamingServerResponse<PublishRes>

        /// Handle the "Subscribe" method.
        ///
        /// - Parameters:
        ///   - request: A streaming request of `SubscribeReq` messages.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A streaming response of `SubscribeRes` messages.
        func subscribe(
            request: GRPCCore.StreamingServerRequest<SubscribeReq>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.StreamingServerResponse<SubscribeRes>
    }

    /// Service protocol for the "MsgLake" service.
    ///
    /// This protocol is higher level than ``StreamingServiceProtocol`` but lower level than
    /// the ``SimpleServiceProtocol``, it provides access to request and response metadata and
    /// trailing response metadata. If you don't need these then consider using
    /// the ``SimpleServiceProtocol``. If you need fine grained control over your RPCs then
    /// use ``StreamingServiceProtocol``.
    internal protocol ServiceProtocol: MsgLake.StreamingServiceProtocol {
        /// Handle the "Publish" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `PublishReq` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A response containing a single `PublishRes` message.
        func publish(
            request: GRPCCore.ServerRequest<PublishReq>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.ServerResponse<PublishRes>

        /// Handle the "Subscribe" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `SubscribeReq` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A streaming response of `SubscribeRes` messages.
        func subscribe(
            request: GRPCCore.ServerRequest<SubscribeReq>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.StreamingServerResponse<SubscribeRes>
    }

    /// Simple service protocol for the "MsgLake" service.
    ///
    /// This is the highest level protocol for the service. The API is the easiest to use but
    /// doesn't provide access to request or response metadata. If you need access to these
    /// then use ``ServiceProtocol`` instead.
    internal protocol SimpleServiceProtocol: MsgLake.ServiceProtocol {
        /// Handle the "Publish" method.
        ///
        /// - Parameters:
        ///   - request: A `PublishReq` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A `PublishRes` to respond with.
        func publish(
            request: PublishReq,
            context: GRPCCore.ServerContext
        ) async throws -> PublishRes

        /// Handle the "Subscribe" method.
        ///
        /// - Parameters:
        ///   - request: A `SubscribeReq` message.
        ///   - response: A response stream of `SubscribeRes` messages.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        func subscribe(
            request: SubscribeReq,
            response: GRPCCore.RPCWriter<SubscribeRes>,
            context: GRPCCore.ServerContext
        ) async throws
    }
}

// Default implementation of 'registerMethods(with:)'.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension MsgLake.StreamingServiceProtocol {
    internal func registerMethods<Transport>(with router: inout GRPCCore.RPCRouter<Transport>) where Transport: GRPCCore.ServerTransport {
        router.registerHandler(
            forMethod: MsgLake.Method.Publish.descriptor,
            deserializer: GRPCProtobuf.ProtobufDeserializer<PublishReq>(),
            serializer: GRPCProtobuf.ProtobufSerializer<PublishRes>(),
            handler: { request, context in
                try await self.publish(
                    request: request,
                    context: context
                )
            }
        )
        router.registerHandler(
            forMethod: MsgLake.Method.Subscribe.descriptor,
            deserializer: GRPCProtobuf.ProtobufDeserializer<SubscribeReq>(),
            serializer: GRPCProtobuf.ProtobufSerializer<SubscribeRes>(),
            handler: { request, context in
                try await self.subscribe(
                    request: request,
                    context: context
                )
            }
        )
    }
}

// Default implementation of streaming methods from 'StreamingServiceProtocol'.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension MsgLake.ServiceProtocol {
    internal func publish(
        request: GRPCCore.StreamingServerRequest<PublishReq>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.StreamingServerResponse<PublishRes> {
        let response = try await self.publish(
            request: GRPCCore.ServerRequest(stream: request),
            context: context
        )
        return GRPCCore.StreamingServerResponse(single: response)
    }

    internal func subscribe(
        request: GRPCCore.StreamingServerRequest<SubscribeReq>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.StreamingServerResponse<SubscribeRes> {
        let response = try await self.subscribe(
            request: GRPCCore.ServerRequest(stream: request),
            context: context
        )
        return response
    }
}

// Default implementation of methods from 'ServiceProtocol'.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension MsgLake.SimpleServiceProtocol {
    internal func publish(
        request: GRPCCore.ServerRequest<PublishReq>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.ServerResponse<PublishRes> {
        return GRPCCore.ServerResponse<PublishRes>(
            message: try await self.publish(
                request: request.message,
                context: context
            ),
            metadata: [:]
        )
    }

    internal func subscribe(
        request: GRPCCore.ServerRequest<SubscribeReq>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.StreamingServerResponse<SubscribeRes> {
        return GRPCCore.StreamingServerResponse<SubscribeRes>(
            metadata: [:],
            producer: { writer in
                try await self.subscribe(
                    request: request.message,
                    response: writer,
                    context: context
                )
                return [:]
            }
        )
    }
}

// MARK: MsgLake (client)

@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension MsgLake {
    /// Generated client protocol for the "MsgLake" service.
    ///
    /// You don't need to implement this protocol directly, use the generated
    /// implementation, ``Client``.
    internal protocol ClientProtocol: Sendable {
        /// Call the "Publish" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `PublishReq` message.
        ///   - serializer: A serializer for `PublishReq` messages.
        ///   - deserializer: A deserializer for `PublishRes` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func publish<Result>(
            request: GRPCCore.ClientRequest<PublishReq>,
            serializer: some GRPCCore.MessageSerializer<PublishReq>,
            deserializer: some GRPCCore.MessageDeserializer<PublishRes>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<PublishRes>) async throws -> Result
        ) async throws -> Result where Result: Sendable

        /// Call the "Subscribe" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `SubscribeReq` message.
        ///   - serializer: A serializer for `SubscribeReq` messages.
        ///   - deserializer: A deserializer for `SubscribeRes` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func subscribe<Result>(
            request: GRPCCore.ClientRequest<SubscribeReq>,
            serializer: some GRPCCore.MessageSerializer<SubscribeReq>,
            deserializer: some GRPCCore.MessageDeserializer<SubscribeRes>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.StreamingClientResponse<SubscribeRes>) async throws -> Result
        ) async throws -> Result where Result: Sendable
    }

    /// Generated client for the "MsgLake" service.
    ///
    /// The ``Client`` provides an implementation of ``ClientProtocol`` which wraps
    /// a `GRPCCore.GRPCCClient`. The underlying `GRPCClient` provides the long-lived
    /// means of communication with the remote peer.
    internal struct Client<Transport>: ClientProtocol where Transport: GRPCCore.ClientTransport {
        private let client: GRPCCore.GRPCClient<Transport>

        /// Creates a new client wrapping the provided `GRPCCore.GRPCClient`.
        ///
        /// - Parameters:
        ///   - client: A `GRPCCore.GRPCClient` providing a communication channel to the service.
        internal init(wrapping client: GRPCCore.GRPCClient<Transport>) {
            self.client = client
        }

        /// Call the "Publish" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `PublishReq` message.
        ///   - serializer: A serializer for `PublishReq` messages.
        ///   - deserializer: A deserializer for `PublishRes` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        internal func publish<Result>(
            request: GRPCCore.ClientRequest<PublishReq>,
            serializer: some GRPCCore.MessageSerializer<PublishReq>,
            deserializer: some GRPCCore.MessageDeserializer<PublishRes>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<PublishRes>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: MsgLake.Method.Publish.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }

        /// Call the "Subscribe" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `SubscribeReq` message.
        ///   - serializer: A serializer for `SubscribeReq` messages.
        ///   - deserializer: A deserializer for `SubscribeRes` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        internal func subscribe<Result>(
            request: GRPCCore.ClientRequest<SubscribeReq>,
            serializer: some GRPCCore.MessageSerializer<SubscribeReq>,
            deserializer: some GRPCCore.MessageDeserializer<SubscribeRes>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.StreamingClientResponse<SubscribeRes>) async throws -> Result
        ) async throws -> Result where Result: Sendable {
            try await self.client.serverStreaming(
                request: request,
                descriptor: MsgLake.Method.Subscribe.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }
    }
}

// Helpers providing default arguments to 'ClientProtocol' methods.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension MsgLake.ClientProtocol {
    /// Call the "Publish" method.
    ///
    /// - Parameters:
    ///   - request: A request containing a single `PublishReq` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    internal func publish<Result>(
        request: GRPCCore.ClientRequest<PublishReq>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<PublishRes>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.publish(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<PublishReq>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<PublishRes>(),
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "Subscribe" method.
    ///
    /// - Parameters:
    ///   - request: A request containing a single `SubscribeReq` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    internal func subscribe<Result>(
        request: GRPCCore.ClientRequest<SubscribeReq>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.StreamingClientResponse<SubscribeRes>) async throws -> Result
    ) async throws -> Result where Result: Sendable {
        try await self.subscribe(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<SubscribeReq>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<SubscribeRes>(),
            options: options,
            onResponse: handleResponse
        )
    }
}

// Helpers providing sugared APIs for 'ClientProtocol' methods.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension MsgLake.ClientProtocol {
    /// Call the "Publish" method.
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    internal func publish<Result>(
        _ message: PublishReq,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<PublishRes>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<PublishReq>(
            message: message,
            metadata: metadata
        )
        return try await self.publish(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "Subscribe" method.
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    internal func subscribe<Result>(
        _ message: SubscribeReq,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.StreamingClientResponse<SubscribeRes>) async throws -> Result
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<SubscribeReq>(
            message: message,
            metadata: metadata
        )
        return try await self.subscribe(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }
}