name: ci
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - develop
      - feature/*
    tags:
      - v*
    paths-ignore:
      - ".github/**"
env:
  img-registry: ghcr.io/h0n9
  img-repository: msg-lake
  img-tag: latest
  img-push: "false"
jobs:
  build-push:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.img-registry }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: "Set env vars (develop, feature)"
        if: ${{ github.ref_name == 'develop' || startsWith(github.ref_name, 'feature') }}
        shell: bash
        run: |
          echo "img-tag=dev-${GITHUB_SHA::6}" >> $GITHUB_ENV
          echo "img-push=true" >> $GITHUB_ENV
      - name: "Set env vars (tag)"
        if: ${{ startsWith(github.ref_name, 'v') }}
        shell: bash
        run: |
          echo "img-tag=${GITHUB_REF_NAME}" >> $GITHUB_ENV
          echo "img-push=true" >> $GITHUB_ENV
      - name: Build Docker image
        uses: docker/build-push-action@v4
        with:
          platforms: linux/amd64,linux/arm64
          push: ${{ env.img-push }}
          tags: ${{ env.img-registry }}/${{ env.img-repository }}:${{ env.img-tag }}
          cache-from: type=gha,scope=msg-lake
          cache-to: type=gha,mode=max,scope=msg-lake
